# Site settings
title: "Martin TOUZOT"
description: "My resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Martin TOUZOT"
resume_title:                   "Computer Science engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "martin.touzot@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "32 yo • martin.touzot@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Working as an computer science engineer in industrial companies, I aim to use image processing to improve computer to human interactions.</p><p>Blending mathematics to sight saves long speeches.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mtouzot"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/martintouzot/"
  # resume_instagram_url:         ""
  resume_website_url:           "https://mtouzot.github.io"
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
